name: Playwright tests

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:  
  test:
    runs-on: ubuntu-latest  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies  
        run: npm install --force 

      - name: Install Playwright  
        run: npx playwright install --with-deps 

      - name: Install Allure reports
        run: npm install -D allure-commandline --force

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,junit --output=allure-results

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Playwright Network
        run: npx playwright PASV

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: allure-results
          retention-days: 30

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-allure
          path: allure-report
          retention-days: 30
         