name: Playwright tests

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:  
  test:
    runs-on: ubuntu-latest  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies  
        run: npm install --force 

      - name: Install Playwright  
        run: npx playwright install --with-deps 

      - name: Install Allure reports
        run: |
          npm install -D allure-commandline --force
          npx allure generate ./allure-results --clean

      - name: Run Playwright test
        run: npx playwright lambdatest