name: testDemo
on:
    pull_request:
        types:
          - opened
          - closed
        branches: 
          - master
          - develop
          - feat/*
          - bugfix/*
          - hotfix/*
          - release/*
    workflow_dispatch:
    push:
        branches:
          - master
          - develop
          - feat/*
          - bugfix/*
          - hotfix/*
          - release/* 
        paths-ignore:
          - '**.md'
          - '**.yml'
          - '**.yaml'
          - '**.json'
          - '**.sh'
    schedule:
        - cron: '0 0 * * *'

jobs: 
    start_project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with: 
                node-version: '18' 
            - name: Install dependencies
              run: npm i --force
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Wait for localhost
              run: |
                 npm run start &
                 until $(curl --output /dev/null --silent --head --fail http://localhost:4200); do
                 echo "Waiting for localhost to be available..."
                 sleep 5
                 done
            # - name: Run tests
            #     - 4200:4200
            #   run: npm run  pojectTest"
            
    bulding_project:
        needs: start_project
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3  # Используйте actions/checkout для клонирования репозитория
          
          - name: Setup Node.js
            uses: actions/setup-node@v2  # Настройте Node.js
            
          - name: Install dependencies
            run: npm ci --force  # Установка зависимостей с принудительным обновлением
          
          - name: Install Playwright with dependencies
            run: npx playwright install --with-deps  # Установите Playwright с зависимостями
          
          - name: Run tests
            run: npx run lambdaTest  # Запуск тестов
    
              